### ISSUE TITLE
search results disappear when the screen is rotated

### ISSUE THREAD

**Issue by xanscale** [Mapwize/mapwize-ui-android#55] opened 2021-03-30 13:55 UTC
**Describe the bug**
Results disappear after screen rotation

**To Reproduce**
I write a search text
view the results
rotate the device
the results disappear

**Expected behavior**
keep result viewed

**Screenshots**
![33ca8e1d-5262-4260-8af8-83d8e13e9630](https://user-images.githubusercontent.com/255819/113000570-3c5ca000-9170-11eb-8298-de70c9b30298.jpeg)

**Smartphone (please complete the following information):**
all device

**Versions (please complete the following information):**
 - `mapwize-ui-android` version: 2.5.3
 - `mapwize-sdk` version: 3.6.3

**Comment by m3ftah** [comment] 2021-03-30 14:18
Hello,
I was not able to reproduce this bug, can you provide me more details?

I use this standard flag for my activity:
`android:configChanges="orientation|screenSize"`

![rotation-search](https://user-images.githubusercontent.com/3371797/113003737-4d5ae080-9173-11eb-818d-3749507aefbc.gif)

**Comment by xanscale** [comment] 2021-03-30 14:28
so activity should implement configChanges?
i think is not a best practice and fragment or view should make a request during onCreate if search box are filled

for example, our activity have many section and 1 of them are mapwize fragment, using configChanges impact on all sections

**Comment by m3ftah** [comment] 2021-03-30 15:06
I can now reproduce this bug, I will look further into it and I will come back to you tomorrow.

**Comment by m3ftah** [comment] 2021-03-31 15:05
Hello,
This issue has been fixed and the PR #59  will be merged tomorrow.

**Closed** 2021-04-01 15:16 UTC
